import { ShieldCheck } from "lucide-react";
import { resendOtpAction, verifyOtpAction } from "../actions";
import { isLocale } from "@/lib/i18n/dictionaries";
import { notFound } from "next/navigation";

export default async function VerifyPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ identifier?: string; error?: string;resent?:string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const ar = locale === "ar"; const query = await searchParams;
  const identifier=query.identifier||"";const emailFlow=identifier.includes("@");
  return <div className="authCard compactAuth"><div className="otpIcon"><ShieldCheck/></div><div className="authHeading centered"><span>{emailFlow?"EMAIL VERIFICATION":"OTP VERIFICATION"}</span><h2>{emailFlow?(ar?"تحقق من بريدك":"Check your email"):(ar?"تحقق من الرمز":"Verify your code")}</h2><p>{emailFlow?(ar?"أرسلنا رابط تأكيد إلى بريدك. افتح أحدث رسالة واضغط رابط تأكيد الحساب.":"We sent a confirmation link. Open the newest email and select the account confirmation link."):(ar?"أدخل الرمز المرسل إلى رقم الهاتف.":"Enter the code sent to your phone.")}</p></div>{query.resent&&<div className="formSuccess">{emailFlow?(ar?"أُعيد إرسال رابط التأكيد.":"The confirmation link was resent."):(ar?"أُعيد إرسال الرمز.":"The code was resent.")}</div>}{query.error&&<div className="formAlert">{ar?"تعذر التحقق أو انتهت صلاحية الرسالة.":"Verification failed or the message expired."}</div>}{!emailFlow&&<form action={verifyOtpAction} className="stackForm"><input type="hidden" name="locale" value={locale}/><label><span>{ar?"رقم الهاتف":"Phone"}</span><input name="identifier" defaultValue={identifier} required/></label><label><span>{ar?"رمز التحقق":"Verification code"}</span><input className="otpInput" name="token" inputMode="numeric" autoComplete="one-time-code" maxLength={10} required/></label><button className="primaryButton wide" type="submit">{ar?"تأكيد الحساب":"Confirm account"}</button></form>}<form action={resendOtpAction} className="resendForm"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="identifier" value={identifier}/><button className="textButton" type="submit">{emailFlow?(ar?"إعادة إرسال رابط التأكيد":"Resend confirmation link"):(ar?"إعادة إرسال الرمز":"Resend code")}</button></form></div>;
}
