import Link from "next/link";
import { notFound } from "next/navigation";
import { BadgeCheck, CheckCircle2, FileCheck2, Fingerprint, LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { isLocale } from "@/lib/i18n/dictionaries";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { StatusBadge } from "@/components/ui/status-badge";

const levelCopy={ar:["حساب مسجل","وسائل الاتصال موثقة","هوية أساسية مقبولة","ملف معزز أو شركة"],en:["Registered account","Verified contact details","Approved basic identity","Enhanced or business file"]};

export default async function TrustCenter({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params;if(!isLocale(locale))notFound();const ar=locale==="ar",user=await requireUser(locale),s=await createClient();
  const [{data:profile},{data:kyc},{data:limits},{data:acceptances},{data:assurance},{count:openOrders},{count:loginEvents}]=await Promise.all([
    s.from("profiles").select("display_name,phone,country_code,city,account_type,kyc_level,terms_accepted_at,terms_version,login_alerts_enabled").eq("id",user.id).single(),
    s.from("kyc_cases").select("status,account_type,submitted_at,reviewed_at,review_notes").eq("user_id",user.id).maybeSingle(),
    s.from("kyc_level_limits").select("fiat_currency,per_order_limit,daily_limit,description_ar,description_en").eq("level",0),
    s.from("legal_acceptances").select("document_key,document_version,accepted_at").eq("user_id",user.id),
    s.auth.mfa.getAuthenticatorAssuranceLevel(),
    s.from("orders").select("id",{count:"exact",head:true}).eq("user_id",user.id).not("status","in",'(completed,cancelled,rejected)'),
    s.from("login_events").select("id",{count:"exact",head:true}).eq("user_id",user.id),
  ]);
  const level=Number(profile?.kyc_level||0);const actualLimits=level===0?limits:(await s.from("kyc_level_limits").select("fiat_currency,per_order_limit,daily_limit,description_ar,description_en").eq("level",level)).data;const checks=[Boolean(profile?.phone),Boolean(profile?.terms_accepted_at),Boolean(kyc?.submitted_at),kyc?.status==="approved",assurance?.currentLevel==="aal2",Boolean(profile?.login_alerts_enabled)];const readiness=Math.round(checks.filter(Boolean).length/checks.length*100);const nextLevel=Math.min(3,level+1);
  return <><div className="pageHeading"><div><span>GULF GATE / TRUST PASSPORT</span><h1>{ar?"جواز الثقة الرقمي":"Digital trust passport"}</h1><p>{ar?"صورة موحدة لمستوى التحقق والأمان والحدود القانونية لحسابك.":"One view of your verification, security posture and account limits."}</p></div><StatusBadge tone={readiness>=80?"success":"warning"}>{readiness}% {ar?"جاهزية":"ready"}</StatusBadge></div>
  <div className="trustHero panel"><div className="trustOrb"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="52"/><circle className="ringValue" cx="60" cy="60" r="52" style={{strokeDashoffset:327-(327*readiness/100)}}/></svg><strong>{readiness}%</strong></div><div><span>VERIFICATION LEVEL</span><h2>L{level} · {levelCopy[locale][level]}</h2><p>{ar?`المستوى التالي: L${nextLevel} — ${levelCopy.ar[nextLevel]}`:`Next level: L${nextLevel} — ${levelCopy.en[nextLevel]}`}</p><Link className="primaryButton" href={`/${locale}/dashboard/kyc`}>{level>=3?(ar?"مراجعة الملف":"Review file"):(ar?"ترقية مستوى التحقق":"Upgrade verification")}</Link></div></div>
  <div className="trustGrid"><section className="panel"><div className="panelHeading"><div><span>IDENTITY & COMPLIANCE</span><h2>{ar?"حالة الثقة":"Trust status"}</h2></div><Fingerprint/></div><div className="trustChecks">{[[BadgeCheck,ar?"حالة KYC":"KYC status",kyc?.status||"not_started",kyc?.status==="approved"],[FileCheck2,ar?"الموافقات القانونية":"Legal acceptances",`${acceptances?.length||0}/3`,(acceptances?.length||0)>=3],[ShieldCheck,ar?"نوع الحساب":"Account type",profile?.account_type||"individual",true]].map(([Icon,label,value,done])=>{const I=Icon as typeof ShieldCheck;return <article key={String(label)} className={done?"done":""}><I/><span><b>{String(label)}</b><small>{String(value)}</small></span>{done&&<CheckCircle2/>}</article>})}</div></section>
  <section className="panel"><div className="panelHeading"><div><span>SECURITY POSTURE</span><h2>{ar?"درع الحساب":"Account shield"}</h2></div><LockKeyhole/></div><div className="trustChecks">{[[ar?"المصادقة الثنائية":"Two-factor authentication",assurance?.currentLevel==="aal2"],[ar?"تنبيهات الدخول":"Login alerts",profile?.login_alerts_enabled],[ar?"سجل الجلسات":"Session history",(loginEvents||0)>0]].map(([label,done])=><article key={String(label)} className={done?"done":""}><ShieldCheck/><span><b>{String(label)}</b><small>{done?(ar?"فعّال":"Active"):(ar?"يحتاج إجراء":"Action required")}</small></span>{done&&<CheckCircle2/>}</article>)}</div><Link className="secondaryButton wide" href={`/${locale}/dashboard/security`}>{ar?"تقوية أمان الحساب":"Strengthen account security"}</Link></section></div>
  <section className="panel"><div className="panelHeading"><div><span>DEMO REQUEST LIMITS</span><h2>{ar?"سقوف المستوى الحالي":"Current level limits"}</h2><p>{ar?"هذه حدود لطلبات الاختبار وليست صلاحية لتنفيذ معاملة.":"These are demo-request limits, not permission to execute a transaction."}</p></div><Sparkles/></div><div className="limitCards">{(actualLimits||[]).map(x=><article key={x.fiat_currency}><span>{x.fiat_currency}</span><div><small>{ar?"لكل طلب":"Per request"}</small><strong>{Number(x.per_order_limit).toLocaleString()}</strong></div><div><small>{ar?"يومياً":"Daily"}</small><strong>{Number(x.daily_limit).toLocaleString()}</strong></div></article>)}</div><div className="trustFoot"><span>{ar?"طلبات مفتوحة":"Open requests"}: <b>{openOrders||0}</b></span><span>{ar?"حالة التنفيذ: مقفول":"Execution: locked"}</span></div></section></>;
}
