import { MailCheck } from "lucide-react";
import { resetPasswordAction, updatePasswordAction } from "../actions";
import { isLocale } from "@/lib/i18n/dictionaries";
import { notFound } from "next/navigation";

export default async function ResetPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ sent?: string; error?: string;mode?:string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const ar = locale === "ar"; const query = await searchParams;
  if(query.mode==="update")return <div className="authCard compactAuth"><div className="otpIcon"><MailCheck/></div><div className="authHeading centered"><span>SET NEW PASSWORD</span><h2>{ar?"كلمة مرور جديدة":"New password"}</h2><p>{ar?"يجب فتح هذه الصفحة من رابط الاستعادة الآمن.":"This page must be opened from the secure recovery link."}</p></div>{query.error&&<div className="formAlert">{ar?"تعذر تحديث كلمة المرور أو انتهت الجلسة.":"Could not update the password or the session expired."}</div>}<form action={updatePasswordAction} className="stackForm"><input type="hidden" name="locale" value={locale}/><label><span>{ar?"كلمة المرور الجديدة":"New password"}</span><input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><label><span>{ar?"تأكيد كلمة المرور":"Confirm password"}</span><input name="confirmation" type="password" minLength={12} autoComplete="new-password" required/></label><button className="primaryButton wide">{ar?"تحديث كلمة المرور":"Update password"}</button></form></div>;
  return <div className="authCard compactAuth"><div className="otpIcon"><MailCheck/></div><div className="authHeading centered"><span>PASSWORD RECOVERY</span><h2>{ar ? "استعادة كلمة المرور" : "Reset password"}</h2><p>{query.sent ? (ar ? "إذا كان البريد مسجلاً، أرسلنا رابطاً آمناً." : "If the email exists, a secure link was sent.") : (ar ? "سنرسل رابطاً محدود الصلاحية إلى بريدك." : "We will send a limited-time link to your email.")}</p></div><form action={resetPasswordAction} className="stackForm"><input type="hidden" name="locale" value={locale}/><label><span>{ar ? "البريد الإلكتروني" : "Email address"}</span><input name="email" type="email" autoComplete="email" required/></label><button className="primaryButton wide" type="submit">{ar ? "إرسال الرابط" : "Send reset link"}</button></form></div>;
}
