import Link from "next/link";
import { LockKeyhole, Mail, ArrowLeft, ArrowRight } from "lucide-react";
import { loginAction } from "../actions";
import { isLocale } from "@/lib/i18n/dictionaries";
import { notFound } from "next/navigation";

export default async function LoginPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ error?: string;next?:string;password_updated?:string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const ar = locale === "ar"; const query = await searchParams; const Arrow = ar ? ArrowLeft : ArrowRight;
  return <div className="authCard"><div className="authHeading"><span>ACCOUNT ACCESS</span><h2>{ar ? "تسجيل الدخول" : "Sign in"}</h2><p>{ar ? "استخدم البريد الإلكتروني أو رقم الهاتف الدولي." : "Use your email or international phone number."}</p></div>{query.password_updated&&<div className="formSuccess">{ar?"تم تحديث كلمة المرور.":"Password updated."}</div>}{query.error && <div className="formAlert">{query.error === "configuration" ? (ar ? "يلزم ربط Supabase أولاً." : "Supabase must be configured first.") : (ar ? "تعذر تسجيل الدخول. تحقق من البيانات." : "Unable to sign in. Check your details.")}</div>}<form action={loginAction} className="stackForm"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="next" value={query.next||""}/><label><span>{ar ? "البريد أو الهاتف" : "Email or phone"}</span><div className="fieldWithIcon"><Mail/><input name="identifier" autoComplete="username" placeholder={ar ? "name@example.com أو +964..." : "name@example.com or +964..."} required/></div></label><label><span>{ar ? "كلمة المرور" : "Password"}</span><div className="fieldWithIcon"><LockKeyhole/><input name="password" type="password" autoComplete="current-password" required/></div></label><div className="formMeta"><span>{ar?"جلسة محمية بملفات ارتباط آمنة":"Secure cookie session"}</span><Link href={`/${locale}/reset-password`}>{ar ? "نسيت كلمة المرور؟" : "Forgot password?"}</Link></div><button className="primaryButton wide" type="submit">{ar ? "دخول آمن" : "Secure sign in"}<Arrow size={18}/></button></form><p className="authFooter">{ar ? "ليس لديك حساب؟" : "No account yet?"} <Link href={`/${locale}/register`}>{ar ? "إنشاء حساب" : "Create account"}</Link></p></div>;
}
