import Link from "next/link";
import { ArrowUpLeft, ArrowUpRight, BadgeCheck, Clock3, Plus, ShieldAlert, WalletCards } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";
import { DataTable } from "@/components/ui/data-table";
import { isLocale } from "@/lib/i18n/dictionaries";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";

export default async function DashboardPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale:raw }=await params;if(!isLocale(raw))notFound();const locale=raw;const ar=locale==="ar";const Arrow=ar?ArrowUpLeft:ArrowUpRight;const user=await requireUser(locale);const supabase=await createClient();
  const [{data:orders},{data:kyc},{count:proofCount},{count:ticketCount}]=await Promise.all([
    supabase.from("orders").select("id,reference_number,order_type,amount_fiat,fiat_currency,network,status,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(8),
    supabase.from("kyc_cases").select("status").eq("user_id",user.id).maybeSingle(),
    supabase.from("payment_proofs").select("id",{count:"exact",head:true}).eq("user_id",user.id),
    supabase.from("support_tickets").select("id",{count:"exact",head:true}).eq("user_id",user.id).in("status",["open","waiting_customer","waiting_staff"]),
  ]);
  const openOrders=(orders||[]).filter(order=>!["completed","cancelled","rejected"].includes(order.status)).length;const stats=[{labelAr:"الطلبات المفتوحة",labelEn:"Open requests",value:String(openOrders),trend:ar?"إدارية فقط":"Administrative only"},{labelAr:"حالة KYC",labelEn:"KYC status",value:kyc?.status||"not_started",trend:ar?"تحقق فعلي":"Live status"},{labelAr:"الإثباتات",labelEn:"Proofs",value:String(proofCount||0),trend:ar?"تخزين خاص":"Private storage"},{labelAr:"تذاكر الدعم",labelEn:"Support tickets",value:String(ticketCount||0),trend:ar?"مفتوحة":"Open"}];
  const rows=(orders||[]).map(order=>[order.reference_number,order.order_type,`${Number(order.amount_fiat).toLocaleString()} ${order.fiat_currency}`,order.network,order.status]);
  return <><div className="pageHeading"><div><span>CLIENT OVERVIEW</span><h1>{ar?"لوحة العميل":"Client dashboard"}</h1><p>{ar?"بيانات فعلية من حسابك — لا تنفيذ مالي في وضع ما قبل الإطلاق.":"Live account data — no financial execution in pre-launch."}</p></div><div className="headingActions"><Link className="secondaryButton" href={`/${locale}/dashboard/sell`}><WalletCards/>{ar?"طلب بيع":"Sell request"}</Link><Link className="primaryButton" href={`/${locale}/dashboard/buy`}><Plus/>{ar?"طلب شراء":"Buy request"}</Link></div></div><div className="metricGrid">{stats.map((stat,index)=><article className="metricCard" key={stat.labelEn}><div className="metricIcon">{index===1?<BadgeCheck/>:index===3?<ShieldAlert/>:<Clock3/>}</div><span>{ar?stat.labelAr:stat.labelEn}</span><strong>{stat.value}</strong><small>{stat.trend}</small></article>)}</div><div className="dashboardGrid"><section className="panel widePanel"><div className="panelHeading"><div><span>RECENT ACTIVITY</span><h2>{ar?"آخر الطلبات":"Recent requests"}</h2></div><Link className="panelLink" href={`/${locale}/dashboard/orders`}>{ar?"عرض الكل":"View all"}<Arrow/></Link></div>{rows.length?<DataTable columns={ar?["المرجع","النوع","المبلغ","الشبكة","الحالة"]:["Reference","Type","Amount","Network","Status"]} rows={rows}/>:<div className="emptyState">{ar?"لا توجد طلبات بعد. أنشئ طلباً تجريبياً للبدء.":"No requests yet. Create a demo request to begin."}</div>}</section><aside className="panel kycPanel"><div className="panelHeading"><div><span>VERIFICATION</span><h2>{ar?"حالة KYC":"KYC status"}</h2></div><StatusBadge tone={kyc?.status==="approved"?"success":"warning"}>{kyc?.status||"not_started"}</StatusBadge></div><div className="kycRing"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="ringValue" cx="60" cy="60" r="50"/></svg><strong>{kyc?.status==="approved"?"100%":kyc?"72%":"0%"}</strong></div><ul className="checkList"><li className={kyc?"done":""}>{ar?"بدء ملف التحقق":"Verification case"}</li><li className={kyc?.status==="approved"?"done":""}>{ar?"مراجعة الامتثال":"Compliance review"}</li><li className={kyc?.status==="approved"?"done":""}>{ar?"الموافقة":"Approval"}</li></ul><Link className="secondaryButton wide" href={`/${locale}/dashboard/kyc`}>{ar?"فتح ملف التحقق":"Open verification"}</Link></aside></div></>;
}
