import { notFound } from "next/navigation";
import { Activity, BrainCircuit, CheckCircle2, Clock3, Search, ShieldAlert, UsersRound } from "lucide-react";
import { isLocale } from "@/lib/i18n/dictionaries";
import { createClient } from "@/lib/supabase/server";
import { StatusBadge } from "@/components/ui/status-badge";
import { completeChecklistAction, createComplianceCaseAction, decideApprovalAction } from "../actions";

export default async function IntelligencePage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {locale}=await params;if(!isLocale(locale))notFound();const ar=locale==="ar",q=await searchParams,s=await createClient(),term=(q.q||"").trim();
  const [{data:cases},{data:approvals},{data:merchants},{data:searchOrders},{data:searchProfiles}]=await Promise.all([
    s.from("compliance_cases").select("id,reference_number,case_type,risk_score,risk_band,priority,stage,title,assigned_to,sla_due_at,created_at,case_checklist_items(id,label_ar,label_en,required,completed,sort_order)").not("stage","in",'(resolved,closed)').order("sla_due_at").limit(50),
    s.from("approval_requests").select("id,action_type,entity_type,entity_id,reason,status,requested_by,expires_at,created_at").eq("status","pending").order("expires_at").limit(20),
    s.from("merchant_metric_snapshots").select("id,merchant_id,completion_rate,appeal_rate,positive_feedback_rate,avg_payment_minutes,response_score,risk_score,period_end,profiles!merchant_metric_snapshots_merchant_id_fkey(display_name,merchant_verified)").order("period_end",{ascending:false}).limit(20),
    term?s.from("orders").select("id,reference_number,status,order_type,amount_fiat,fiat_currency,user_id").ilike("reference_number",`%${term}%`).limit(10):Promise.resolve({data:[]}),
    term?s.from("profiles").select("id,display_name,phone,kyc_level,account_type").or(`display_name.ilike.%${term}%,phone.ilike.%${term}%`).limit(10):Promise.resolve({data:[]}),
  ]);
  // Server-rendered operational snapshot; current time is intentionally captured once per request.
  // eslint-disable-next-line react-hooks/purity
  const now=Date.now(),open=cases?.length||0,overdue=(cases||[]).filter(c=>new Date(c.sla_due_at).getTime()<now).length,critical=(cases||[]).filter(c=>c.risk_score>=75).length,pending=approvals?.length||0;
  return <><div className="pageHeading"><div><span>GULF GATE / OPERATIONS INTELLIGENCE</span><h1>{ar?"مركز القرار والامتثال":"Decision & compliance intelligence"}</h1><p>{ar?"قضايا 360°، SLA، موافقة ثنائية، ومؤشرات تجار — دون تنفيذ مالي.":"360° cases, SLA, dual control and merchant intelligence — without financial execution."}</p></div><StatusBadge tone="danger">LIVE_TRADING=false</StatusBadge></div>
  <section className="panel"><form className="globalSearch"><Search/><input name="q" defaultValue={term} placeholder={ar?"ابحث بالمرجع أو الهاتف أو اسم العميل":"Search reference, phone or customer"}/><button className="primaryButton">{ar?"بحث شامل":"Global search"}</button></form>{term&&<div className="searchResults">{(searchProfiles||[]).map(p=><article key={p.id}><UsersRound/><span><b>{p.display_name||p.phone||p.id.slice(0,8)}</b><small>{p.account_type} · KYC L{p.kyc_level}</small></span></article>)}{(searchOrders||[]).map(o=><article key={o.id}><Activity/><span><b>{o.reference_number}</b><small>{o.order_type} · {o.amount_fiat} {o.fiat_currency} · {o.status}</small></span></article>)}</div>}</section>
  <div className="metricGrid adminMetrics">{[[BrainCircuit,ar?"قضايا مفتوحة":"Open cases",open],[Clock3,ar?"تجاوزت SLA":"SLA overdue",overdue],[ShieldAlert,ar?"حرجة":"Critical",critical],[CheckCircle2,ar?"موافقات معلقة":"Pending approvals",pending]].map(([Icon,label,value])=>{const I=Icon as typeof Activity;return <article className="metricCard" key={String(label)}><div className="metricIcon"><I/></div><span>{String(label)}</span><strong>{String(value)}</strong></article>})}</div>
  <div className="intelligenceGrid"><section className="caseStack">{(cases||[]).map(c=><details className={`panel caseCard risk-${c.risk_band}`} key={c.id}><summary><span><StatusBadge tone={c.risk_score>=75?"danger":c.risk_score>=50?"warning":"info"}>{c.risk_band} · {c.risk_score}</StatusBadge><b>{c.reference_number} · {c.title}</b><small>{c.case_type} · {c.stage}</small></span><span><b>{new Date(c.sla_due_at).getTime()<now?(ar?"متأخرة":"Overdue"):(ar?"قبل":"Due")} {new Date(c.sla_due_at).toLocaleString(ar?"ar-IQ":"en-GB")}</b></span></summary><div className="caseChecklist">{(c.case_checklist_items||[]).sort((a:{sort_order:number},b:{sort_order:number})=>a.sort_order-b.sort_order).map((item:{id:string;label_ar:string;label_en:string;completed:boolean;required:boolean})=><form action={completeChecklistAction} key={item.id}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="completed" value={item.completed?"false":"true"}/><button className={item.completed?"complete":""}><CheckCircle2/><span>{ar?item.label_ar:item.label_en}{item.required&&<small>{ar?"إلزامي":"Required"}</small>}</span></button></form>)}</div></details>)}{!cases?.length&&<div className="panel emptyState">{ar?"لا توجد قضايا مفتوحة":"No open cases"}</div>}</section>
  <aside className="panel"><div className="panelHeading"><div><span>NEW INVESTIGATION</span><h2>{ar?"إنشاء قضية يدوية":"Create manual case"}</h2></div><BrainCircuit/></div><form action={createComplianceCaseAction} className="stackForm"><input type="hidden" name="locale" value={locale}/><label><span>{ar?"النوع":"Type"}</span><select name="caseType">{["manual","account","kyc","order","proof","p2p","dispute"].map(x=><option key={x}>{x}</option>)}</select></label><label><span>{ar?"العنوان":"Title"}</span><input name="title" required minLength={4}/></label><label><span>{ar?"معرّف العميل (اختياري)":"Customer UUID (optional)"}</span><input name="subjectUserId"/></label><label><span>{ar?"معرّف الطلب (اختياري)":"Order UUID (optional)"}</span><input name="orderId"/></label><label><span>{ar?"درجة المخاطر":"Risk score"}</span><input name="riskScore" type="number" min="0" max="100" defaultValue="25"/></label><label><span>{ar?"الملخص":"Summary"}</span><textarea name="summary" rows={4}/></label><button className="primaryButton">{ar?"فتح القضية":"Open case"}</button></form></aside></div>
  <section className="panel"><div className="panelHeading"><div><span>FOUR-EYES CONTROL</span><h2>{ar?"موافقات تحتاج موظفاً ثانياً":"Dual-control approvals"}</h2></div><CheckCircle2/></div><div className="approvalGrid">{(approvals||[]).map(a=><article key={a.id}><span><b>{a.action_type}</b><small>{a.entity_type} · {a.entity_id.slice(0,12)} · {a.reason}</small></span><form action={decideApprovalAction}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="id" value={a.id}/><input name="note" placeholder={ar?"ملاحظة القرار":"Decision note"}/><button name="decision" value="approve" className="primaryButton">{ar?"موافقة":"Approve"}</button><button name="decision" value="reject" className="dangerButton">{ar?"رفض":"Reject"}</button></form></article>)}</div></section>
  <section className="panel"><div className="panelHeading"><div><span>MERCHANT INTELLIGENCE</span><h2>{ar?"أداء التجار ومخاطرهم":"Merchant performance & risk"}</h2></div><UsersRound/></div><div className="merchantScoreGrid">{(merchants||[]).map(m=>{const p=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;return <article key={m.id}><div><b>{p?.display_name||m.merchant_id.slice(0,8)}</b><StatusBadge tone={m.risk_score>=50?"danger":"success"}>Risk {m.risk_score}</StatusBadge></div><dl><span>Completion <strong>{m.completion_rate}%</strong></span><span>Appeals <strong>{m.appeal_rate}%</strong></span><span>Feedback <strong>{m.positive_feedback_rate}%</strong></span><span>Response <strong>{m.response_score}%</strong></span></dl></article>})}</div></section></>;
}
