import Link from "next/link";
import { notFound } from "next/navigation";
import { Activity, AlertTriangle, BadgeCheck, Clock3, Filter, UserRoundCog } from "lucide-react";
import { isLocale } from "@/lib/i18n/dictionaries";
import { createClient } from "@/lib/supabase/server";
import { StatusBadge } from "@/components/ui/status-badge";
import { assignOpsItemAction, reviewKycAction, reviewProofAction, updateOrderStatusAction } from "../actions";

type QueueItem = { id:string; kind:"kyc"|"order"|"proof"|"dispute"; reference:string; customer:string; status:string; currency?:string; network?:string; city?:string; assignedTo?:string|null; createdAt:string; files?:{bucket:string;path:string;name:string}[] };

export default async function OpsQueuePage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<Record<string,string|undefined>>}) {
  const {locale}=await params;if(!isLocale(locale))notFound();const ar=locale==="ar", filters=await searchParams,supabase=await createClient();
  const [{data:kyc},{data:orders},{data:proofs},{data:disputes},{data:staff},{data:activity}]=await Promise.all([
    supabase.from("kyc_cases").select("id,user_id,status,assigned_to,created_at,profiles!kyc_cases_user_id_fkey(display_name,phone),kyc_documents(storage_path,original_filename)").in("status",["submitted","under_review","resubmission_required"]),
    supabase.from("orders").select("id,reference_number,status,fiat_currency,network,assigned_to,created_at,profiles!orders_user_id_fkey(display_name,phone),payment_methods(city)").not("status","in",'(completed,cancelled,rejected)'),
    supabase.from("payment_proofs").select("id,order_id,status,assigned_to,storage_path,original_filename,created_at,profiles!payment_proofs_user_id_fkey(display_name,phone),orders(reference_number,fiat_currency,network)").in("status",["uploaded","under_review","resubmission_required"]),
    supabase.from("disputes").select("id,status,assigned_to,created_at,p2p_orders(reference_number,fiat_currency,network)").not("status","in",'(closed,resolved_buyer,resolved_seller)'),
    supabase.from("staff_roles").select("user_id,role,profiles!staff_roles_user_id_fkey(display_name)"),
    supabase.from("audit_logs").select("id,action,entity_type,entity_id,created_at").order("created_at",{ascending:false}).limit(12),
  ]);
  const first=<T,>(v:T|T[]|null):T|null=>Array.isArray(v)?v[0]||null:v;
  const allItems:QueueItem[]=[
    ...(kyc||[]).map(x=>{const p=first(x.profiles),docs=x.kyc_documents||[];return{id:x.id,kind:"kyc" as const,reference:`KYC-${x.id.slice(0,8)}`,customer:p?.display_name||p?.phone||x.user_id.slice(0,8),status:x.status,assignedTo:x.assigned_to,createdAt:x.created_at,files:docs.map((d:{storage_path:string;original_filename:string})=>({bucket:"kyc-documents",path:d.storage_path,name:d.original_filename}))}}),
    ...(orders||[]).map(x=>{const p=first(x.profiles),m=first(x.payment_methods);return{id:x.id,kind:"order" as const,reference:x.reference_number,customer:p?.display_name||p?.phone||"—",status:x.status,currency:x.fiat_currency,network:x.network,city:m?.city,assignedTo:x.assigned_to,createdAt:x.created_at}}),
    ...(proofs||[]).map(x=>{const p=first(x.profiles),o=first(x.orders);return{id:x.id,kind:"proof" as const,reference:o?.reference_number||`PROOF-${x.id.slice(0,8)}`,customer:p?.display_name||p?.phone||"—",status:x.status,currency:o?.fiat_currency,network:o?.network,assignedTo:x.assigned_to,createdAt:x.created_at,files:[{bucket:"payment-proofs",path:x.storage_path,name:x.original_filename}]}}),
    ...(disputes||[]).map(x=>{const o=first(x.p2p_orders);return{id:x.id,kind:"dispute" as const,reference:o?.reference_number||`DSP-${x.id.slice(0,8)}`,customer:"P2P",status:x.status,currency:o?.fiat_currency,network:o?.network,assignedTo:x.assigned_to,createdAt:x.created_at}}),
  ];
  const items=allItems.filter(x=>(!filters.kind||x.kind===filters.kind)&&(!filters.status||x.status===filters.status)&&(!filters.currency||x.currency===filters.currency)&&(!filters.network||x.network===filters.network)&&(!filters.assignee||x.assignedTo===filters.assignee)&&(!filters.q||`${x.reference} ${x.customer}`.toLowerCase().includes(filters.q.toLowerCase()))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  const staffOptions=(staff||[]).map(s=>({id:s.user_id,name:first(s.profiles)?.display_name||s.user_id.slice(0,8),role:s.role}));
  const waiting=items.filter(x=>x.status.includes("resubmission")||x.status.includes("awaiting")).length,review=items.filter(x=>x.status.includes("review")||x.status==="investigating").length,escalated=items.filter(x=>x.status.includes("hold")||x.kind==="dispute").length;
  return <><div className="pageHeading"><div><span>OPERATIONS / UNIFIED QUEUE</span><h1>{ar?"غرفة العمليات":"Operations queue"}</h1><p>{ar?"مراجعة وتعيين واتخاذ إجراء بدون نسخ UUID.":"Review, assign and act without copying UUIDs."}</p></div><StatusBadge tone="danger">LIVE_TRADING=false</StatusBadge></div>
    <div className="metricGrid adminMetrics">{[[Clock3,ar?"مفتوح":"Open",items.length],[BadgeCheck,ar?"قيد المراجعة":"In review",review],[UserRoundCog,ar?"بانتظار العميل":"Waiting customer",waiting],[AlertTriangle,ar?"مصعّد":"Escalated",escalated]].map(([Icon,label,value])=>{const I=Icon as typeof Clock3;return <article className="metricCard" key={String(label)}><div className="metricIcon"><I/></div><span>{String(label)}</span><strong>{String(value)}</strong></article>})}</div>
    <section className="panel"><form className="opsFilters"><Filter/><input name="q" defaultValue={filters.q} placeholder={ar?"مرجع، عميل، هاتف":"Reference, customer, phone"}/><select name="kind" defaultValue={filters.kind||""}><option value="">{ar?"كل الأنواع":"All types"}</option>{["kyc","order","proof","dispute"].map(v=><option key={v}>{v}</option>)}</select><select name="currency" defaultValue={filters.currency||""}><option value="">{ar?"كل العملات":"All currencies"}</option>{["USD","AED","IQD"].map(v=><option key={v}>{v}</option>)}</select><select name="network" defaultValue={filters.network||""}><option value="">{ar?"كل الشبكات":"All networks"}</option><option>TRC20</option><option>ERC20</option></select><select name="assignee" defaultValue={filters.assignee||""}><option value="">{ar?"كل الموظفين":"All assignees"}</option>{staffOptions.map(s=><option value={s.id} key={`${s.id}-${s.role}`}>{s.name} · {s.role}</option>)}</select><button className="secondaryButton">{ar?"تطبيق":"Apply"}</button></form></section>
    <div className="opsLayout"><section className="opsQueue">{items.length?items.map(item=><details className="panel opsItem" key={`${item.kind}-${item.id}`}><summary><span><StatusBadge tone={item.kind==="dispute"?"danger":"info"}>{item.kind}</StatusBadge><b>{item.reference}</b><small>{item.customer} · {new Date(item.createdAt).toLocaleString(ar?"ar-IQ":"en-GB")}</small></span><span><StatusBadge tone={item.status.includes("reject")?"danger":"warning"}>{item.status}</StatusBadge><small>{item.currency||"—"} · {item.network||"—"}</small></span></summary><div className="opsItemBody">{item.files?.length?<div className="documentList">{item.files.map(f=><Link target="_blank" rel="noreferrer" href={`/api/files/${f.bucket}/${f.path}`} key={f.path}>{f.name}</Link>)}</div>:null}<form action={assignOpsItemAction} className="inlineOpsForm"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="kind" value={item.kind}/><input type="hidden" name="id" value={item.id}/><select name="assignee" required defaultValue={item.assignedTo||""}><option value="" disabled>{ar?"عيّن موظفاً":"Assign staff"}</option>{staffOptions.map(s=><option value={s.id} key={`${item.id}-${s.id}-${s.role}`}>{s.name} · {s.role}</option>)}</select><input name="note" placeholder={ar?"ملاحظة داخلية":"Internal note"}/><button className="secondaryButton">{ar?"تعيين وحفظ":"Assign & save"}</button></form>{item.kind==="kyc"&&<QuickReview locale={locale} id={item.id} kind="kyc"/>}{item.kind==="proof"&&<QuickReview locale={locale} id={item.id} kind="proof"/>}{item.kind==="order"&&<QuickReview locale={locale} id={item.id} kind="order"/>}</div></details>):<div className="panel emptyState">{ar?"لا توجد عناصر مطابقة.":"No matching queue items."}</div>}</section><aside className="panel activityFeed"><div className="panelHeading"><div><span>AUDIT STREAM</span><h2>{ar?"آخر النشاطات":"Recent activity"}</h2></div><Activity/></div>{(activity||[]).map(a=><div key={a.id}><i/><span><b>{a.action}</b><small>{a.entity_type} · {String(a.entity_id||"").slice(0,8)} · {new Date(a.created_at).toLocaleString(ar?"ar-IQ":"en-GB")}</small></span></div>)}</aside></div></>;
}

function QuickReview({locale,id,kind}:{locale:"ar"|"en";id:string;kind:"kyc"|"proof"|"order"}){const action=kind==="kyc"?reviewKycAction:kind==="proof"?reviewProofAction:updateOrderStatusAction;const statuses=kind==="kyc"?["under_review","approved","rejected","resubmission_required"]:kind==="proof"?["under_review","approved","rejected","resubmission_required"]:["awaiting_kyc","awaiting_payment","proof_uploaded","under_review","payment_confirmed","compliance_hold","approved","cancelled","rejected","refund_required"];return <form action={action} className="inlineOpsForm"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="id" value={id}/><select name="status">{statuses.map(s=><option key={s}>{s}</option>)}</select><input name="note" placeholder={locale==="ar"?"سبب القرار":"Decision note"}/><button className="primaryButton">{locale==="ar"?"تحديث الحالة":"Update status"}</button></form>}
